parameters:
    admin.forumformhandler.class: Movidon\ForumBundle\Form\Handler\ForumFormHandler
    admin.forumcategoryformhandler.class: Movidon\ForumBundle\Form\Handler\ForumCategoryFormHandler

services:
    admin.admin_forum_form_handler:
        class: %admin.forumformhandler.class%
        arguments: [@doctrine.orm.entity_manager]
    admin.admin_forum_category_form_handler:
        class: %admin.forumcategoryformhandler.class%
        arguments: [@doctrine.orm.entity_manager]