blog:
    path: /blog
    defaults: { _controller: BlogBundle:Blog:index }

blog_view_post:
    path: /blog/p/{slug}
    defaults: { _controller: BlogBundle:Blog:view }

blog_view_post_by_user:
    path: /blog/u/{slug}
    defaults: { _controller: BlogBundle:Blog:viewUserPosts }

blog_view_post_by_tag:
    path: /blog/t/{slug}
    defaults: { _controller: BlogBundle:Blog:viewPostsByTag }
