forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /

message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /

image:
    resource: "@ImageBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /bo

category:
    resource: "@CategoryBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /