security:
    encoders:
        Movidon\BackendBundle\Entity\AdminUser: { algorithm: sha512, iterations: 10 }
        #Ecommerce\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #user:
        #    entity: { class: Ecommerce\UserBundle\Entity\User, property: email }
        admin_user:
            entity: { class: Movidon\BackendBundle\Entity\AdminUser, property: username }
        in_memory:
            memory:
                users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN', 'ROLE_ALLOWED_TO_SWITCH' ] }

    firewalls:
        admin:
            pattern: ^/bo
            provider: admin_user
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: /bo
                always_use_default_target_path: true
            logout:
                path: /bo/logout
        #user:
        #    pattern: ^/
        #    provider: user
        #    anonymous: ~
        #    form_login:
        #       login_path: login
        #       check_path: login_check
        #       success_handler: cartujano.security.authentication.success_handler
        #       default_target_path: /u/mi-cuenta
        #    logout:
        #       path: logout
        #    remember_me:
        #       key: %secret%
        #       lifetime: 5184000

    access_control:
        - { path: ^/bo/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bo/.*, role: ROLE_SUPER_ADMIN }
        - { path: ^/u/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/email-disponible, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/recuperar-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/reenviar-correo-de-activacion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/cambiar-password/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/u/valida-tu-cuenta, roles: ROLE_USER_NOT_VALIDATED }
        - { path: ^/tu-pedido, roles: ROLE_USER }
        - { path: ^/u/*, roles: ROLE_USER }
