super_admin_user_index:
    pattern: /
    defaults: { _controller: BackendBundle:User:list }

super_admin_user_edit:
    pattern: /edit/{id}
    defaults: { _controller: BackendBundle:User:edit }

super_admin_user_delete:
    pattern: /delete/{id}
    defaults: { _controller: BackendBundle:User:delete }

super_admin_user_create:
    pattern: /create
    defaults: { _controller: BackendBundle:User:create }

super_admin_user_profile:
    pattern: /profile/{id}
    defaults: { _controller: BackendBundle:User:profile }

super_admin_user_update_profile:
    pattern: /update/profile/{id}
    defaults: { _controller: BackendBundle:User:updateProfile }

super_admin_user_toggle_ban:
    pattern: /toggle-ban/{id}
    defaults: { _controller: BackendBundle:User:toggleBan }
