admin_login:
    pattern: /login
    defaults: { _controller: BackendBundle:Backend:login }

admin_login_check:
    pattern: /login_check

admin_logout:
    pattern: /logout

admin_register:
    pattern: /register
    defaults: { _controller: BackendBundle:Backend:register }

admin:
    pattern: /
    defaults: #{ _controller: BackendBundle:Backend:example }
        _controller: FrameworkBundle:Redirect:redirect
        route: admin_index
        permanent: true # this is for 301

admin_index:
    pattern: /dashboard
    defaults: { _controller: BackendBundle:Backend:index }

admin_tags:
    resource: "@BackendBundle/Resources/config/routing/tag.yml"
    prefix: /tag/

admin_categories:
    resource: "@BackendBundle/Resources/config/routing/category.yml"
    prefix: /category/

admin_posts:
    resource: "@BackendBundle/Resources/config/routing/post.yml"
    prefix: /post/

admin_messages:
    resource: "@BackendBundle/Resources/config/routing/message.yml"
    prefix: /messages/

admin_forum:
    resource: "@BackendBundle/Resources/config/routing/forum.yml"
    prefix: /forum/

#admin_categories:
#    resource: "@BackendBundle/Resources/config/routing/category.yml"
#    prefix: /category/

admin_user:
    resource: "@BackendBundle/Resources/config/routing/user.yml"
    prefix: /u/

super_admin:
    resource: "@BackendBundle/Resources/config/routing/superadmin.yml"
    prefix: /sa/
