frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Frontend:index }

who_we_are:
    path:     /who-we-are
    defaults: { _controller: FrontendBundle:Frontend:whoAreWe }

view_profile:
    path:     /profile/{slug}
    defaults: { _controller: FrontendBundle:Frontend:viewProfile }